---
# tasks file for php

- name: remove ppa for PHP 5.6
  file: /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list 
  state: absent
  tags:
    - php

- name: update caches
  shell: apt-get update
  tags:
    - php
 tasks file for php

- name: add ppa for PHP 7.0
  shell: add-apt-repository ppa:ondrej/php

# Common configurations to be run on all hosts
# http://www.sitepoint.com/run-multiple-versions-php-one-server/
- name: Install default packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - gcc
    - make
    - libc-dev
    - libtool
    - re2c
    - autoconf
    - automake
    - git
    - curl
    - libcurl3
    - libcurl3-dev
    - php5-curl
  tags:
    - apt
    - php

- name: download file and force basic auth
  get_url: url=http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb dest=/opt/
  become: yes
  tags:
    - php

- name: download file and force basic auth
  get_url: url=http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb dest=/opt/
  become: yes
  tags:
    - php

- name: Remove bison 3
  apt: pkg={{item}} state=absent
  with_items:
    - bison
    - libbison-dev
  tags:
    - php

- name: Install libbison
  apt: deb=/opt/libbison-dev_2.7.1.dfsg-1_amd64.deb
  become: yes
  tags:
    - php

- name: Install bison
  apt: deb=/opt/bison_2.7.1.dfsg-1_amd64.deb
  become: yes
  tags:
    - php

- name: Creates directory
  file: path={{item}} state=directory owner=vagrant group=vagrant
  with_items:
    - /opt/source/php-src
  become: yes
  tags:
    - php

- name: clone php-src
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=master force=yes
  tags:
    - php

- name: checkout PHP 7.2
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=master clone=no force=yes
  tags:
    - php

- name: build PHP 7.2
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-7.2" --with-config-file-path="/usr/local/etc/php-7.1" --enable-mbstring --enable-tokenizer --with-curl=/usr --enable-phar --with-sqlite3 --enable-json --disable-all; make -j {{ ansible_processor_count * 2 }} ; make install
  tags:
    - php

- name: php72 config
  file:
    path: /usr/local/etc/php-7.2/
    state: directory
    mode: 0755

- name: php72 config memory_limit
  lineinfile:
    dest: /usr/local/etc/php-7.2/php.ini
    line: 'memory_limit = -1'
    state: present
    create: yes

- name: php72 symlink
  file: src=/usr/local/bin/php-7.2/bin/php dest=/usr/local/bin/php72 state=link
  tags:
    - php

- name: checkout PHP 7.1
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-7.1.1 clone=no force=yes
  tags:
    - php

- name: build PHP 7.1
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-7.1" --with-config-file-path="/usr/local/etc/php-7.1" --enable-mbstring --enable-tokenizer --with-curl=/usr --enable-phar --with-sqlite3 --enable-json --disable-all; make -j {{ ansible_processor_count * 2 }} ; make install
  tags:
    - php

- name: php71 symlink
  file: src=/usr/local/bin/php-7.1/bin/php dest=/usr/local/bin/php71 state=link
  tags:
    - php

- name: php71 config
  file:
    path: /usr/local/etc/php-7.1/
    state: directory
    mode: 0755

- name: php71 config memory_limit
  lineinfile:
    dest: /usr/local/etc/php-7.1/php.ini
    line: 'memory_limit = -1'
    state: present
    create: yes

- name: checkout PHP 7.0
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-7.0.15 clone=no force=yes
  tags:
    - php

- name: build PHP 7.0
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-7.0" --with-config-file-path="/usr/local/etc/php-7.0" --enable-mbstring --enable-tokenizer  --with-curl=/usr --enable-phar --with-sqlite3 --enable-json --enable-hash --disable-all; make -j {{ ansible_processor_count * 2 }} ; make install
  tags:
    - php

- name: php70 config
  file:
    path: /usr/local/etc/php-7.0/
    state: directory
    mode: 0755

- name: php70 config memory_limit
  lineinfile:
    dest: /usr/local/etc/php-7.0/php.ini
    line: 'memory_limit = -1'
    state: present
    create: yes

- name: php symlink (for running exakat)
  file: src=/usr/local/bin/php-7.0/bin/php dest=/usr/local/bin/php state=link
  tags:
    - php

- name: checkout PHP 5.6
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-5.6.30 clone=no force=yes
  tags:
    - php

- name: build PHP 5.6
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-5.6" --with-config-file-path="/usr/local/etc/php-5.6" --enable-mbstring --enable-tokenizer --with-sqlite3 --enable-json --disable-all; make -j {{ ansible_processor_count * 2 }} ; make install
  tags:
    - php

- name: php56 config
  file:
    path: /usr/local/etc/php-5.6/
    state: directory
    mode: 0755

- name: php56 config memory_limit
  lineinfile:
    dest: /usr/local/etc/php-5.6/php.ini
    line: 'memory_limit = -1'
    state: present
    create: yes

- name: php 5.6 symlink
  file: src=/usr/local/bin/php-5.6/bin/php dest=/usr/local/bin/php56 state=link
  tags:
    - php

- name: clean php-src
  file: path=/opt/source/php-src state=absent
  tags:
    - php
