---
# Common configurations to be run on all hosts
# http://www.sitepoint.com/run-multiple-versions-php-one-server/
- name: Install default packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - gcc
    - make
    - libc-dev
    - libtool
    - re2c
    - autoconf
    - automake
    - git
    - curl
    - libcurl3
    - libcurl3-dev
    - php5-curl
  tags:
    - apt
    - php

- include: include_bison

- name: Creates directory
  file: path={{item}} state=directory owner=vagrant group=vagrant
  with_items:
    - /opt/source/php-src
  become: yes
  tags:
    - php

- name: clone php-src
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=master force=yes
  tags:
    - php

- include: include_php73
- include: include_php72
- include: include_php71
- include: include_php70
- include: include_php56

- name: clean php-src
  file: path=/opt/source/php-src state=absent
  tags:
    - php

